spring:
  datasource:
    druid:
      test1:
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test1?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
        initialSize: 5
        minIdle: 5
        maxActive: 20
        filters: conn,config,stat,slf4j
      test2:
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test2?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
        initialSize: 5
        minIdle: 5
        maxActive: 20
        filters: conn,config,stat,slf4j
merchants:
  #数组加map
  merchant:
    - mername: 127.0.0.1
      isftp: Y
      ftphost: 127.0.0.1
      ftpport: 22
      mccode: "020089"
      isclosed: N
    - mername: 127.0.0.1
      isftp: Y
      ftphost: 127.0.0.1
      ftpport: 22
      mccode: "020088"
      isclosed: N
mybatis-plus:
  config-location: